### ISSUE TITLE
STM32F100C8 compatibility

### ISSUE THREAD

**Issue by tom2238** [supurloop/ssf#1]
Hi. For some days I am looking for Reed-Solomon decoder/encoder in C for STM32 MCU. RS from SSF framework look good for embedded systems. In next days (weeks?) i will try running on STM32. And my question. How many memory is consumed in encoder only mode? My STM32F100C8 MCU has only 8 kb of SRAM. Is this enough? Thank you.

**Comment by supurloop** [comment]
Hi, memory usage depends on the RS configuration in ssfport.h. All the memory usage is stack-based, no heap is used.  I have used the RS encoder on a PIC with 4KB program memory and 256 bytes of RAM.  However the decoder requires more program and data memory, but 8KB RAM should be doable. The two configuration parameters that drive the memory usage are SSF_RS_MAX_CHUNK_SIZE and SSF_RS_MAX_SYMBOLS. Reducing the size of those will directly reduce the require amount of stack space. The encoder and decoder can handle messages > the CHUNK size by appending additional SYMBOLS at the end of the message for each chunk.
